### ISSUE TITLE
Assembly doesn't have a Strong Name

### ISSUE THREAD

**Issue by iNyssa** [airbrake/sharpbrake#104] opened 2019-03-05 09:36 UTC
Is there a reason why the assembly when it is shipped over nuget is not signed?
I can't implement the assembly if it doesn't have a strong name.

I could sign and compile the source myself. But via nuget I would expect this to happen automatically.

**Comment by rbalabukh** [comment] 2019-03-05 16:40
Duplicate of #102

**Closed by rbalabukh** 2019-03-05 16:40 UTC
